<a href="https://colab.research.google.com/github/BosenkoTM/ProgA/blob/main/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%B4%D0%BB%D1%8F_%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%BE%D0%B2_%D0%BB%D0%B5%D0%BA%D1%86_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Создание массивов

Массив
Для начала нужно импортировать модуль.

In [1]:
import numpy as np

Создание массива из списка:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
type(a)

[1 2 3 4 5]


numpy.ndarray

**Numpy** автоматически вычисляет тип, узнать его можно обратившись к полю **dtype**

In [ ]:
print(arr.dtype) # int64

int64


In [ ]:
arr = np.array([1, 2, 3.14])
print(arr.dtype) # float64

float64


Если **numpy** не может подобрать тип, то он сохраняет все как есть, тип в таком случае получается **object**

Также важным атрибутом массивов является их форма:

In [ ]:
arr = np.array([1, 2, 3])
print(arr.shape) # (3,)

(3,)


Функция **array()** трансформирует вложенные последовательности в многомерные массивы. Тип элементов массива зависит от типа элементов исходной последовательности (но можно и переопределить его в момент создания).

In [ ]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

Функция **array()** не единственная функция для создания массивов. Обычно элементы массива вначале неизвестны, а массив, в котором они будут храниться, уже нужен. Поэтому имеется несколько функций для того, чтобы создавать массивы с каким-то исходным содержимым (по умолчанию тип создаваемого массива — float64).

Функция **zeros()** создает массив из нулей, а функция **ones()** — массив из единиц. Обе функции принимают кортеж с размерами, и аргумент dtype:

In [ ]:
np.zeros((3, 5))
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

Функция **eye()** создаёт единичную матрицу (двумерный массив)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Функция **empty()** создает массив без его заполнения. Исходное содержимое случайно и зависит от состояния памяти на момент создания массива (то есть от того мусора, что в ней хранится):

In [2]:
np.empty((3, 3))
np.empty((3, 3))

array([[3.8725545e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

Вообще, при использовании **arange()** с аргументами типа **float**, сложно быть уверенным в том, сколько элементов будет получено (из-за ограничения точности чисел с плавающей запятой). Поэтому, в таких случаях обычно лучше использовать функцию **linspace()**, которая вместо шага в качестве одного из аргументов принимает число, равное количеству нужных элементов:

In [ ]:
np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно

**fromfunction()**: применяет функцию ко всем комбинациям индексов

In [ ]:
def f1(i, j):
    return 3 * i + j

print(np.fromfunction(f1, (3, 4)))
print(np.fromfunction(f1, (3, 3)))

[[0. 1. 2. 3.]
 [3. 4. 5. 6.]
 [6. 7. 8. 9.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


По форме можно определить кол-во элементов по каждой из осей / каждому из измерений.

Так, для двумерного массива получится следующий результат:

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.shape) # (3, 2)

(3, 2)


Чтобы узнать полное кол-во элементов массиве есть поле size:

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.size) # 6

6


# Печать массивов

Если массив слишком большой, чтобы его печатать, NumPy автоматически скрывает центральную часть массива и выводит только его уголки.

In [ ]:
print(np.arange(0, 3000, 1))

[   0    1    2 ... 2997 2998 2999]


Если вам действительно нужно увидеть весь массив, используйте функцию numpy.set_printoptions:

# Базовые операции

Математические операции над массивами выполняются поэлементно. Создается новый массив, который заполняется результатами действия оператора.

In [ ]:
import sys
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a + b)
print(a - b)
print(a * b)
print(a / b)  # При делении на 0 возвращается inf (бесконечность)
print(a ** b)
print(a % b)  # При взятии остатка от деления на 0 возвращается 0

[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[        inf 30.         20.         16.66666667]
[     1     30   1600 125000]
[0 0 0 2]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in remainder
  # This is added back by InteractiveShellApp.init_path()


Также можно производить математические операции между массивом и числом. В этом случае к каждому элементу прибавляется (или что вы там делаете) это число.

In [ ]:
print(a + 1)
print(a ** 3)
print(a < 35)

[21 31 41 51]
[  8000  27000  64000 125000]
[ True  True False False]


**NumPy** также предоставляет множество математических операций для обработки массивов:

In [ ]:
print(np.cos(a))
print(np.arctan(a))
print(np.sinh(a))

array([2.42582598e+08, 5.34323729e+12, 1.17692633e+17, 2.59235276e+21])

Многие унарные операции, такие как, например, вычисление суммы всех элементов массива, представлены также и в виде методов класса **ndarray**.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a))
print(a.sum())
print(a.min())
print(a.max())

21
21
1
6


# Индексы, срезы, итерации

Одномерные массивы осуществляют операции индексирования, срезов и итераций очень схожим образом с обычными списками и другими последовательностями Python (разве что удалять с помощью срезов нельзя).

In [ ]:
a = np.arange(10) ** 3
print(a)
print(a[1])
print(a[3:7])
a[3:7] = 8
print(a)
print(a[::-1])


for i in a:
    print(i ** (1/3))

[  0   1   8  27  64 125 216 343 512 729]
1
[ 27  64 125 216]
[  0   1   8   8   8   8   8 343 512 729]
[729 512 343   8   8   8   8   8   1   0]
0.0
1.0
2.0
2.0
2.0
2.0
2.0
6.999999999999999
7.999999999999999
8.999999999999998


У многомерных массивов на каждую ось приходится один индекс. Индексы передаются в виде последовательности чисел, разделенных запятыми (то бишь, кортежами):

In [ ]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

print(b[2,3])  # Вторая строка, третий столбец
print(b[(2,3)])
print(b[2][3]) # Можно и так
print(b[:,2])  # Третий столбец
print(b[:2])  # Первые две строки
print(b[1:3, : : ])  # Вторая и третья строки

23
23
23
[ 2 12 22 32 42]
[[ 0  1  2  3]
 [10 11 12 13]]
[[10 11 12 13]
 [20 21 22 23]]


# Манипуляции с формой

 у массива есть форма (**shape**), определяемая числом элементов вдоль каждой оси:

In [ ]:
a
a.shape

(10,)

Форма массива может быть изменена с помощью различных команд:

In [ ]:
a = np.array(([[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]))
print(a.ravel())  # Делает массив плоским
a.shape = (6, 2)  # Изменение формы
print(a)
print(a.transpose())  # Транспонирование
print(a.reshape((3, 4)))  # Изменение формы

[  0   1   2  10  12  13 100 101 102 110 112 113]
[[  0   1]
 [  2  10]
 [ 12  13]
 [100 101]
 [102 110]
 [112 113]]
[[  0   2  12 100 102 112]
 [  1  10  13 101 110 113]]
[[  0   1   2  10]
 [ 12  13 100 101]
 [102 110 112 113]]


# Объединение массивов

Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack.

hstack() объединяет массивы по первым осям, vstack() — по последним:

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Функция **column_stack()** объединяет одномерные массивы в качестве столбцов двумерного массива:

In [ ]:
np.column_stack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Аналогично для строк имеется функция row_stack().

In [ ]:
np.row_stack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Разбиение массива

Используя **hsplit()** вы можете разбить массив вдоль горизонтальной оси, указав либо число возвращаемых массивов одинаковой формы, либо номера столбцов, после которых массив разрезается "ножницами":

In [ ]:
a = np.arange(12).reshape((2, 6))
a
np.hsplit(a, 3)  # Разбить на 3 части
np.hsplit(a, (3, 4))  # Разрезать a после третьего и четвёртого столбца

[array([[0, 1, 2],
        [6, 7, 8]]), array([[3],
        [9]]), array([[ 4,  5],
        [10, 11]])]

Функция vsplit() разбивает массив вдоль вертикальной оси, а array_split() позволяет указать оси, вдоль которых произойдет разбиение.

# NumPy  random

1. Создавать списки, используя встроенный модуль random, а затем преобразовывать их в **numpy.array**:

In [ ]:
import numpy as np
import random
np.array([random.random() for i in range(10)])

array([0.6573008 , 0.29354028, 0.14640781, 0.51997406, 0.41071396,
       0.09867844, 0.16981854, 0.54959453, 0.91482495, 0.85526269])

2.Для создания массивов со случайными элементами служит модуль **numpy.random**.

In [ ]:
import numpy as np  # Импортировать numpy и писать np.random
np.random
import numpy.random as rand  # Можно и присвоить отдельное имя. Вопрос вкуса
rand

In [ ]:
print(np.random.sample())
print(np.random.sample(3))
print(np.random.sample((2, 3)))
    

0.5654166150766796
[0.68378918 0.32126419 0.99948942]
[[0.46302914 0.80124331 0.13505769]
 [0.97246115 0.11903287 0.73531642]]


Без аргументов возвращает просто число в промежутке [0, 1), с одним целым числом - одномерный массив, с кортежем - массив с размерами, указанными в кортеже (все числа - из промежутка [0, 1)).

С помощью функции randint или random_integers можно создать массив из целых чисел. Аргументы: low, high, size: от какого, до какого числа (randint не включает в себя это число, а random_integers включает), и size - размеры массива.

In [ ]:
print(np.random.randint(0, 3, 10))
print(np.random.random_integers(0, 3, 10))
print(np.random.randint(0, 3, (2, 10)))
